name: My First Workflow 

on: push

jobs:
    frist_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: list and read files
          run: |
            echo "my first github actions job"
            ls -ltra 
            cat README.md 
        
        - name: generate ASCII artwork
          run: cowsay -f dragon "Run for cover, I am a DRAGON...RAWR" >> dragon.txt

        # - name: list files
        #   run: ls 

        # - name: read file
        #   run: cat README.md 