name: My First Workflow 

on: push

jobs:
    frist_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4
          
        - name: welcome message
          run: echo "my first github actions job"

        - name: list files
          run: ls 

        - name: read file
          run: cat README.md 